### ISSUE TITLE
Detection fails on minimal docker image

### ISSUE THREAD

**Issue by rmg** [lovell/detect-libc#10]
In a docker image that has been stripped of all non-essential files, the libc detection comes back with `''`.

Other than the node app installed under `/app`, the entire rest of the image consists of this:
```
-rw-r--r--   1 root     root          108 Nov 22 00:26 /etc/passwd
-rw-r--r--   1 root     root           36 Nov 22 00:26 /etc/group
-rw-r--r--   1 root     root          388 Nov 22 00:26 /etc/ld.so.preload
-rw-r--r--   1 root     root          259 Nov 22 00:26 /etc/nsswitch.conf
-rwxr-xr-x   1 root     root      1738176 Jun 18 11:09 /lib/x86_64-linux-gnu/libc.so.6
-rw-r--r--   1 root     root        22952 Jun 18 11:09 /lib/x86_64-linux-gnu/libnss_dns.so.2
-rw-r--r--   1 root     root        84856 Jun 18 11:09 /lib/x86_64-linux-gnu/libresolv.so.2
-rwxr-xr-x   1 root     root       137384 Jun 18 11:09 /lib/x86_64-linux-gnu/libpthread.so.0
-rw-r--r--   1 root     root      1051056 Jun 18 11:09 /lib/x86_64-linux-gnu/libm.so.6
-rw-r--r--   1 root     root        31784 Jun 18 11:09 /lib/x86_64-linux-gnu/librt.so.1
-rw-r--r--   1 root     root        90096 Dec 25  2014 /lib/x86_64-linux-gnu/libgcc_s.so.1
-rw-r--r--   1 root     root        14664 Jun 18 11:09 /lib/x86_64-linux-gnu/libdl.so.2
-rw-r--r--   1 root     root        47712 Jun 18 11:09 /lib/x86_64-linux-gnu/libnss_files.so.2
-rw-r--r--   1 root     root      1008120 Dec 25  2014 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
-rwxr-xr-x   1 root     root       140928 Jun 18 11:09 /lib64/ld-linux-x86-64.so.2
-rwxr-xr-x   1 root     root     35197069 Nov 22 00:26 /bin/node
```

From reading the code, I expect the filesystem based detection to match the one entry under `/lib`, but it doesn't.

I'm trying to reproduce this with tests now, but wanted to open this sooner rather than later.

**Comment by rmg** [comment]
Found it.. There is no `/usr/sbin`, so when the filesystem detection runs it fails before even looking at the results.

**Comment by coreprocess** [comment]
@rmg Thanks for your report! Can you provide a ready-to-use Dockerfile for this case? (we could add this to our test-suite)

**Comment by coreprocess** [comment]
@rmg good catch! Thank you! We will fix this.

**Comment by rmg** [comment]
Here's the `Dockerfile` for reproducing it in the test suite:
```Dockerfile
FROM node:8.8.1
RUN mkdir -p /rootfs
RUN ldd /bin/sh \
        /usr/local/bin/node \
        /lib/x86_64-linux-gnu/libnss_files.so.* \
        /lib/x86_64-linux-gnu/libnss_dns.so.* \
    | grep -o -e '\/\(usr\|lib\)[^ :]\+' \
    | sort -u | tee /rootfs.list \
 && echo /bin/sh >> /rootfs.list

# The use of 'tar | tar' here is a quick'n'dirty replacement for rsync without
# adding any deps: rsync --files-from=/rootfs.list -L -pog / /rootfs/
RUN cat /rootfs.list | tar -T- -cphf- | tar -C /rootfs -xpf-

# noop
FROM scratch
COPY --from=0 /rootfs/ /
```

**Comment by rmg** [comment]
(with a bonus of some pretty useful sh-fu for creating super minimal docker images for node apps)

**Comment by coreprocess** [comment]
@rmg Fix is coming soon, see https://github.com/lovell/detect-libc/pull/11/files

**Comment by lovell** [comment]
You spend all that effort building a minimalist image and then someone goes and runs `npm install` ;)

**Comment by rmg** [comment]
@lovell in case it isn't obvious from the `Dockerfile` I contributed to that PR, the `npm install` is done in the first phase of the build. The final image doesn't have `npm` in it to be able to run `npm install` ;-)

The problem came up because when `npm install` was run, `detect-libc` could recognize the system, but later when running the final image `detect-libc` could _no longer_ recognize the system and tried to tell `grpc` to load a different `.node` binary than what it installed.

**Comment by rmg** [comment]
For completeness, this is closer to the actual `Dockerfile` that gets used:

```Dockerfile
### Build image
FROM node:8.8.1
RUN mkdir -p /rootfs
ADD . /rootfs/app/
RUN cd /rootfs/app && npm install --production
# Find all system provided .so's referenced by node and any binary addons
# libnss_files and libnss_dns are included manually because they are loaded by
# glibc using dlopen instead of linking, so they don't get detected, but are
# required for node to work properly in most cases.
RUN { \
        ldd /usr/local/bin/node \
            /lib/x86_64-linux-gnu/libnss_files.so.* \
            /lib/x86_64-linux-gnu/libnss_dns.so.*; \
        find /rootfs/app -type f -name '*.node' | xargs ldd; \
        true; \
    } \
    | grep -o -e '\/\(usr\|lib\)[^ :]\+' \
    | sort -u | tee /rootfs.list

# The use of 'tar | tar' here is a quick'n'dirty replacement for rsync without
# adding any deps: rsync --files-from=/rootfs.list -L -pog / /rootfs/
RUN cat /rootfs.list | tar -T- -cphf- | tar -C /rootfs -xpf-

### Production image
FROM scratch
COPY --from=0 /rootfs/ /
WORKDIR /app
CMD ["/usr/local/bin/node", "."]
```

Caveat: this makes the app run as `root` inside the container. Throwing non-root permissions in to the mix is relatively easy, but adds more complexity to the example than is necessary to demonstrate the `.so` reduction technique. Also note the lack of `/bin/sh`, which means the production image section of the `Dockerfile` can't even use `RUN`.

**Comment by lovell** [comment]
@rmg My comment was intended as a joke, sorry, but thank you very much for sharing some great ideas here.

Whilst we're doing tips for smaller production Docker images, I find removing all the "compile"-time Typescript source/definitions helps, something like:

```Dockerfile
RUN npm install --production && find node_modules -type f -iname '*.ts' -delete
```

**Comment by coreprocess** [comment]
@rmg thanks for the detailed explanation! The saving is quite significant and your approach can be used as an alternative to an alpine linux based approach. I love your idea!

**Comment by lovell** [comment]
v1.0.3 now available via npm. Thank you both again for the report and the fix!
