### ISSUE TITLE
Plans for version 2

### ISSUE THREAD

**Issue by lovell** [lovell/detect-libc#14]
This module is downloaded about a million times every day (!), and its logic is perhaps run hundreds of times every second.

Making changes to something this highly depended upon is a little frightening, but if we can reduce the time/energy cost then I think it will be worthwhile.

The logic hasn't changed in over four years and (rather amazingly) it all still works, but the ecosystem around it has improved so it's time for this module to do likewise.

Goals:

* Expose functionality via both async and sync functions
* Reduce require-time CPU and I/O cost, defer as much logic as possible until functions are called
* Only spawn a child process where absolutely necessary, and consolidate into a single call
* The requirements of both `@mapbox/node-pre-gyp` and `prebuild` become first-class concerns (perhaps others? Parcel? Electron?)
* Support Node.js 8+, drop support for Node.js 6 and earlier
* Migrate CI to GitHub Actions, add more recent OS and Node.js versions to integration tests
* Use Node.js 12+ native [report](https://nodejs.org/dist/latest-v17.x/docs/api/report.html) feature where available, allows family detection and glibc version (but not musl version)

Progress:

* [x] Readme - https://github.com/lovell/detect-libc/tree/main
* [x] Implement new API
* [x] Unit tests - https://github.com/lovell/detect-libc/actions/runs/1708403127
* [x] Integration tests (26 combinations) - https://github.com/lovell/detect-libc/actions/runs/1708403128
* [x] JSDocs
* [x] TypeScript type definitions
* [x] Verify `prebuild` will work
* [x] Verify `@mapbox/node-pre-gyp` will work

**Comment by coreprocess** [comment]
@lovell a million times per day, crazy!

**Comment by styfle** [comment]
> Use Node.js 12+ native report feature where available, allows family detection and glibc version (but not musl version)

Would it make sense to add musl detection to the report as well? 

I started a related PR here: https://github.com/nodejs/node/pull/41338

**Comment by lovell** [comment]
@styfle Yes, the addition of `process.report.getReport().header.muslVersionRuntime` would be useful, but I'm unsure if musl exposes `__libc_version` via its external API - see https://git.musl-libc.org/cgit/musl/tree/src/internal/version.c

**Comment by lovell** [comment]
The new `main` branch (which will become the default branch) has all the latest code and tests.

If anyone would like to help review this, add more containers for integration testing or submit further improvements, all these things are very welcome.

https://github.com/lovell/detect-libc/tree/main

I plan to publish this as v2.0.0, probably later this week.

**Comment by lovell** [comment]
v2.0.0 now available. Please open a new issue if you discover any problems. PRs to add more containers for integration testing are welcome too.
