### ISSUE TITLE
Handle ldd --version with exitcode 1 and output on stderr

### ISSUE THREAD

**Issue by coreprocess** [lovell/detect-libc#2]
```ldd --version``` on alpine:3.6 returns with exitcode 1 and prints information on ```stderr```. This szenario should be supported by the library.

**Comment by coreprocess** [comment]
See https://github.com/mapbox/node-pre-gyp/issues/325#issuecomment-340118295 for more.

**Comment by lovell** [comment]
Hello Niklas, good catch, thanks for reporting this change in `ldd` behaviour. I've published `detect-libc` v1.0.1 to include support for this.

**Comment by coreprocess** [comment]
Thanks!
