### ISSUE TITLE
Enhancement: add container-based integration tests

### ISSUE THREAD

**Issue by lovell** [lovell/detect-libc#3]
Thanks to @core-process for this excellent suggestion.

Can initially be based on the great work in https://github.com/core-process/detect-libc-async/tree/master/tests/docker

**Comment by coreprocess** [comment]
I can provide a pull request, in case you are interested.

**Comment by lovell** [comment]
@core-process Yes please, if you have the time.

**Comment by coreprocess** [comment]
@lovell see https://github.com/lovell/detect-libc/pull/6

**Comment by coreprocess** [comment]
@lovell see https://github.com/mapbox/node-pre-gyp/issues/325#issuecomment-340225511

**Comment by lovell** [comment]
Merged #6, thank you!
