### ISSUE TITLE
Proposal: reduce integration build run-time by using pre-built docker images

### ISSUE THREAD

**Issue by coreprocess** [lovell/detect-libc#7]
@lovell We could reduce run-time of the integration tests significantly, if we decide to pre-build the docker images. In case we want to do this, we need a docker registry; e.g. we could use a free quay.io account for that.

**Comment by lovell** [comment]
It's probably worth checking to see if we can take advantage of any of the following:

Centos:
* https://hub.docker.com/r/openshift/nodejs-010-centos7/
* https://hub.docker.com/r/centos/nodejs-4-centos7/
* https://hub.docker.com/r/centos/nodejs-6-centos7/
* https://hub.docker.com/r/centos/nodejs-8-centos7/

Alpine:
* https://hub.docker.com/r/mhart/alpine-node/

Debian:
* https://hub.docker.com/r/nodesource/node/

**Comment by coreprocess** [comment]
Thanks, I will have a look!

**Comment by coreprocess** [comment]
Closing this issue now. @lovell please re-open, if you do not agree.
