### ISSUE TITLE
Improvement: set-up a more complete test matrix for integration builds 

### ISSUE THREAD

**Issue by coreprocess** [lovell/detect-libc#8]
Related to https://github.com/mapbox/node-pre-gyp/issues/325.

From my point of view we need to consider two dimensions in regard to the integration tests:
* Node.js versions (0.10.x, 0.12.x, 4.x, 6.x, 8.x)
* Linux distributions and their versions (e.g. Alpine Linux v3.6, Alpine Linux v3.4, CentOS Linux 7 (Core), ...)

I think we can test both dimensions independently without creating a full blown matrix. This approach should be enough to proof reliability of ```lovell/detect-libc```. In case you agree, we just need to define the set of Linux distributions and versions we want to support.

Note: even though we do not need a full-blown matrix, we need to run the tests on every selected distribution/distri-version for Node.js 0.10.x and 8.x/latest. Reason is the fallback to filesystem detection method on Node.js 0.10.x. Still we can use a sparse test matrix :-)... (at least from my point of view).

**Comment by coreprocess** [comment]
Related to https://github.com/mapbox/node-pre-gyp/pull/326.

**Comment by coreprocess** [comment]
Incomplete proposal:

| Distribution | Docker Registry | Versions |
| - | - | - |
| Alpine Linux | https://hub.docker.com/_/alpine/ | 3.1, 3.2, 3.3, 3.4, 3.5, 3.6 |
| Debian | https://hub.docker.com/_/debian/ | wheezy, jessie, stretch |
| Ubuntu | https://hub.docker.com/_/ubuntu/ | 14.04, 16.04, 17.04, 17.10 |
| openSUSE | https://hub.docker.com/_/opensuse/ | 13.3, 42.1, 42.2, 42.3 |
| CentOS | https://hub.docker.com/_/centos/ | 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4 |
| Oracle Linux | https://hub.docker.com/_/oraclelinux/ | 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4 |
| Amazon Linux | https://hub.docker.com/_/amazonlinux/ | 2016.09, 2017.03, 2017.09 |

More items:
* https://hub.docker.com/_/clearlinux/
* https://hub.docker.com/r/nodeos/nodeos/
* https://hub.docker.com/u/gentoo/

**Comment by lovell** [comment]
I agree with testing only Node v0.10 and 8 on each OS. Hopefully we'll be able to find ready-built images for as many necessary combinations as possible.

For Node v0.10 we may not have to worry so much about the derivatives, e.g. testing Debian will cover Ubuntu.

We should add Amazon Linux (a RHEL 6+7 hybrid) to this list also due to its use with Lambda.

**Comment by coreprocess** [comment]
I agree, but we should avoid non-maintained community images.

It is better if we use well maintained base images (e.g. official images or maintained by a lively community). In case we can use the script from [nodesource.com](https://github.com/nodesource/distributions), setting up a custom image based on a well maintained base image is very cheap and just 3 lines of code (see [nodejs-8.x-centos.dockerfile](https://github.com/lovell/detect-libc/blob/master/tests/integration/nodejs-8.x-centos.dockerfile)). We could even generate them via template. And building such images is very fast and can be done during the integration test itself (as it is done at the moment) without increasing the run-time of the test to a pain barrier.

In case we cannot use prepared rpm/deb/whatever-packages or the installer from nodesource.com, we have to build Node.js and this increases run-time significantly (e.g. [nodejs-0.10.48-alpine.dockerfile](https://github.com/lovell/detect-libc/blob/master/tests/integration/nodejs-0.10.48-alpine.dockerfile)). In case we have a couple of these images, we should think about pre-building them.

**Comment by coreprocess** [comment]
@lovell I have setup a first draft regarding an enhanced test matrix. See https://github.com/lovell/detect-libc/pull/9 for more.

**Comment by coreprocess** [comment]
Closing this issue. @lovell if you do not agree, please reopen.
